project:
  type: website

website:
  title: "Libro Econometría"
  navbar:
    left:
      - href: index.qmd
        text: Acerca de
      - href: about_fundamentos_r.qmd
        text: Home
    
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Fundamentos de R"
        contents:
          - href: about_fundamentos_r.qmd
            text: Introducción
            
      - section: "Series de Tiempo"
        contents:
          - href: ts_e_uni.qmd
            text: Series de Tiempo Estacionarias (Univariadas)
          - href: ts_ne_uni.qmd
            text: Series de Tiempo No Estacionarias (Univariadas)
          - href: operaciones.qmd
            text: Series de Tiempo Estacionarias (Multivariadas)
            
      - section: "Econometría Espacial"
        contents:
          - href: about_econometria_espacial.qmd
            text: Introducción
          - href: spatial_stats.qmd
            text: Estadistica y Relaciones Espaciales
          - href: w.qmd
            text: Matriz de Pesos Espaciales (W)            
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

