project:
  type: website
  output-dir: docs

website:
  title: "Libro Econometría"
  
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Bienvenido(s)
      - section: "Fundamentos de R"
        contents:
          - href: operaciones.qmd
            text: Primeros Pasos y Estructuras de Datos
          - href: estructuras.qmd
            text: Estructuras
          - href: primer_dataset.qmd
            text: Introducción al manejo de datos en R
      - section: "Fundamentos de Python"
        contents:
          - href: variables_operadores.ipynb
            text: Introducción y Operadores
          - href: colecciones.ipynb
            text: Colecciones o Estructuras de Datos
            
      - section: "Series de Tiempo"
        contents:
          - href: ts_e_uni.qmd
            text: Series de Tiempo Estacionarias (Univariadas)
          - href: ts_ne_uni.qmd
            text: Series de Tiempo No Estacionarias (Univariadas)
            
      - section: "Econometría Espacial"
        contents:
          - href: spatial_stats.qmd
            text: Estadistica y Relaciones Espaciales
          - href: w.qmd
            text: Matriz de Pesos Espaciales (W)            
    
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

