---
title: "Variables y Operadores"
editor: visual
jupyter: python3
---

## Introducción

Python es un lenguaje de programación interpretado, de alto nivel, lento, facil de aprender y comunmente usado en analisis y manejo de datos por lo cual es multiparadigma.

Python se puede ejecutar de dos principales maneras, desde un editor de texto como VSCode o desde un Notebook como lo puede ser Jupyter Notebook, Colab o Pycharm, la ventaja de los segundos es que nos permiten trabajar con texto enriquecido y ver los outputs por partes de nuestro codigo, los cual nos da una flexibilidad muy alta.

## Comentarios

Es una buena practica comentar nuestro codigo, esto significa ir colocando texto no ejecutable que explique que esta haciendo nuestro codigo, esto facilitará más adelante nuestra vida al corregir el codigo y a otras personas que quieran entender lo que estamos haciendo, para comentar el codigo usamos el #, con esto el texto que se encuentre despues del numeral no será ejecutado

``` python
#Esto es un comentario
```

## Variables y tipo de objetos

Diremos que una variable es un "contenedor de información" en la que podemos "guardar" diferntes objetos, generalmente se escriben en minúscula, sin espacios ni tildes, comas, puntos, signos de interrogación o cualquier otro caracter a excepción del guión bajo, en Python no es necesario declarar explicitamente el tipo de objeto que contiene una variable o colección.

Para declarar una variable usamos:

``` python
nombre_de_la_variable_0 = "Valor De La Variable"
```

Los objetos que guardamos en las variables pueden ser de diferentes tipos y dependiendo del tipo de objeto cambiamos la forma de guardarlo

``` python
objeto_int = 2
objeto_string = "Hola Mundo"
objeto_float = 2.5
objeto_bool = False
```

Puede darse el caso de que requiero convertir un objeto de un tipo a otro tipo, para esto debo usar el type casting el cual es alguna de las siguientes funciones según corresponda

``` python
int(n_objeto)
float(n_objeto)
str(n_objeto)
bool(n_objeto)
```

## Operadores aritméticos

Python incluye varios operadores aritméticos que se utilizan para realizar operaciones matemáticas en números. Los operadores aritméticos incluyen:

-   `+`: suma dos números

-   `-`: resta dos números

-   `*` : multiplica dos números

-   `/`: divide dos números (devuelve un número flotante)

-   `//`: divide dos números (devuelve la parte entera de la división)

-   `%`: devuelve el resto de la división entre dos números

-   `**`: eleva un número a una potencia

A continuación, algunos ejemplos:

``` python
a = 10
b = 5

suma = a + b
resta = a - b
multiplicacion = a * b
division = a / b
division_entera = a // b
resto = a % b
potencia = a ** 2
```

También podemos utilizar operadores aritméticos con variables y asignar el resultado a otra variable:

``` python
a = 10
b = 5

c = a + b
d = a * b

print(c) # Output: 15
print(d) # Output: 50

```

Además, Python sigue las reglas convencionales de precedencia de operadores aritméticos. Esto significa que las operaciones dentro de paréntesis se evalúan primero, seguidas de la exponenciación, la multiplicación y la división, y finalmente la suma y la resta. Podemos utilizar paréntesis para forzar un orden de evaluación diferente

## Operadores Logicos y de comparación
